import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "primereact/resources/themes/soho-light/theme.css"; // 🎨 Tema de PrimeReact
import "primereact/resources/primereact.min.css";               // ⚙️ Core de PrimeReact
import "primeicons/primeicons.css";                             // 🔣 Iconos de PrimeReact
// import "primeflex/primeflex.css";                               // 📐 Utilidades CSS de PrimeFlex (grid, flex, spacing)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
